### ISSUE TITLE
 Không thoát khỏi được sau khi nhấn vào notification

### ISSUE THREAD

**Issue by khangzxrr** [khangzxrr/pure-pixel-frontend#63]
-  Không thoát khỏi được sau khi nhấn vào notification

Watch the screen recording here: https://jam.dev/c/895656b9-2ea9-4898-b562-4c7d58a62c72

-------------------------------------

**Website URL:**
[http://localhost:3000/test/profile](http://localhost:3000/test/profile)

**Device and browser info:**
Chrome 129.0.6668.89 (2048x1034) | Linux (x86) x86_64

**Date and time:**
October 3rd 2024 | 6:43pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/895656b9-2ea9-4898-b562-4c7d58a62c72](https://jam.dev/c/895656b9-2ea9-4898-b562-4c7d58a62c72)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by TrungNguyenHRZ** [comment]
đã fix nhó
